version: '3.8'

services:
  web:
    container_name: tiptrac-web
    build: .
    ports:
      - "80:80"  # Map port 80 of host to port 80 of container
    volumes:
      - ./app:/code/app  # Mount the host's 'app' folder into '/code/app' in the container
    depends_on:
      - db
    networks:
      - tiptrac-network
    environment:
      DATABASE_URL: "mysql+pymysql://mladen:password@db/tiptracdb"
    
  db:
    container_name: tiptrac-mysql
    image: mysql:8
    networks:
      - tiptrac-network
    environment:
      MYSQL_DATABASE: tiptracdb # Database name
      MYSQL_USER: mladen  # New user
      MYSQL_PASSWORD: pwd403shr  # Password for new user
      MYSQL_ROOT_PASSWORD: 4x{;tXaTw~DWAhoWGRI.
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  tiptrac-network:
    name: tiptrac-network

volumes:
  mysql-data:
